### ISSUE TITLE
Error while calling the function

### ISSUE THREAD

**Issue by volkanarslan83** [GeoBosh/cvar#1]
Hello,
Thanks for the code. However, I am getting error while running the code.

The error I get: Error in get(as.character(FUN), mode = "function", envir = envir) :

**Comment by GeoBosh** [comment]
Thanks for the report but could you include also the code that gives this error?

**Comment by volkanarslan83** [comment]
cvar::VaR(abcd) where abcd is my excel file including returns

**Comment by GeoBosh** [comment]
`cvar` expects a distribution, not raw data (whatever you mean by 'abcd is my excel file'). You need to fit a model to your data and supply it in the form of a distribution to `cvar`. For example, let's assume that your data are in vector `x`.  I will create a simulated vector here for a complete example:
```
x <- rnorm(100, mean = 0.01, sd = 0.05)
```
If you think that the data are i.i.d. Gaussian, you can fit a normal distribution (this is your model) by:
```
mu <- mean(x)
st.dev <- sd(x)
```
To compute Var at 5%, you could do:
```
cvar::VaR(qnorm, x = 0.05, mean = mu, sd = st.dev)
```
This gave me  0.07870364 but since the data in this example are simulated, you will get a somewhat different result if you repeat the calculations. There are further example in the documentation, see `?cvar::VaR` or visit https://geobosh.github.io/cvar/reference/VaR.html .

If you want a more sophisticated model, fit it with a suitable package and submit the distribution to cvar::VaR, there is an example with a GARCH(1,1) model in the documentation.

**Comment by volkanarslan83** [comment]
Thanks for the answer. My last question: how can I calculate Var and ES for the real data of the companies using WRDS?

**Comment by GeoBosh** [comment]
Sorry but this is quite off topic, you will need to look around, google should find some examples for you. Good luck.
